name: helpalapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: "^0.1.3"
  #FIREBASE
  firebase_core: any
  firebase_messaging: any
  firebase_database: any
  cloud_firestore: any
  firebase_storage: any
  firebase_auth: any
  firebase_crashlytics: any

  google_sign_in: any
  
  #LOCAL KEYS
  shared_preferences: any
  hive: any
  #GOOGLE MAPS
  google_maps_flutter: any
  flutter_polyline_points: any
  google_maps_place_picker: any
  location: any
  latlong: any

  #background_location: "^0.4.1"
  #permission_handler: "5.1.0+2"
  #flutter_background_geolocation: "^1.9.0"
  #background_fetch: "^0.6.0"
  #meta: "^1.2.0"

  #EXTRA TOOLS
  audio_recorder: any
  audioplayer: any
  minimize_app: any
  path_provider: any
  image_picker: any
  rflutter_alert: any
  share: any
  #flutter_sound: "^6.4.2+1"
  sliding_up_panel: any
  bubble: any
  #time formater
  intl: any
  
  provider: any
  geocoder: any
  #tuple: "^1.0.3"
  #characters: "^1.0.0"
  #image_cropper: "1.3.1"
  #image_picker_type: ^0.0.4
  overlay_support: any
  overlay_container: any
  #fl_chart: "^0.12.2"
  #mailer: "^3.2.1"
  
  #notifications
  flutter_local_notifications: any


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/mapstyle.txt
    - assets/audios/
    - assets/images/logo.png
    - assets/images/mainlogo.png
    - assets/images/logoTop.png
    - assets/images/logoBottom.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/bubble.png
    - assets/images/greenbg.png
    - assets/images/bluebg.png
    - assets/images/mapdummy.png
    - assets/images/marker_pin_helper.png
    - assets/images/marker_pin_helpee.png
    - assets/images/avatar.png
    - assets/images/divider.png
    - assets/images/worker.png
    - assets/images/call.png
    - assets/images/recording.png
    - assets/images/stop.png
    - assets/images/stopred.png
    - assets/images/play.png
    - assets/images/map.png
    - assets/images/cnicf.png
    - assets/images/cnicb.png
    - assets/images/vehreg.png
    - assets/images/helpersigninbg.png
    - assets/images/mapicons/plumber.png
    - assets/images/mapicons/electrician.png
    - assets/images/mapicons/rider.png
    - assets/images/mapicons/washerman.png
    - assets/images/mapicons/tailor.png
    - assets/images/mapicons/cab.png
    - assets/images/mapicons/deliverybike.png
    - assets/images/mapicons/deliverypickup.png
    - assets/images/services/logo1.png
    - assets/images/services/logo2.png
    - assets/images/services/logo3.png
    - assets/images/services/logo4.png
    - assets/images/services/logo5.png
    - assets/images/services/logo6.png
    - assets/images/services/logo7.png
    - assets/images/services/logo8.png
    - assets/images/services/cabnbike.png
    - assets/images/services/allLogos.png
    - assets/images/services/deliverybike.png
    - assets/images/services/deliverypickup.png
    - assets/images/icons/coupons.png
    - assets/images/icons/history.png
    - assets/images/icons/donate.png
    - assets/images/icons/notifications.png
    - assets/images/icons/privacy.png
    - assets/images/icons/help.png
    - assets/images/icons/feedback.png
    - assets/images/icons/waiting.png
    - assets/images/icons/wallet.png
    - assets/images/icons/ac.png
    - assets/images/icons/boy.png
    - assets/images/icons/caution.png
    - assets/images/icons/money.png
    - assets/images/icons/basket.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-SemiBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
